name: Deploy to EC2

on:
  push:
    branches:
      - main
  # Optional manual trigger
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to production EC2 instance
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/zenvy  # Ensure this points to the absolute path of your app on the EC2 machine
          git pull origin main
          
          # 1. Update Backend
          cd server
          npm install
          npx prisma generate
          
          # Start or Restart backend using PM2
          pm2 restart zenvy-server || pm2 start server.js --name zenvy-server
          
          # 2. Update Frontend
          cd ../client
          npm install
          npm run build
          
          # Start or Restart Next.js using PM2
          pm2 restart zenvy-client || pm2 start npm --name zenvy-client -- start
