name: Deploy to EC2

on:
  push:
    branches:
      - main
  # Optional manual trigger
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to production EC2 instance
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          if [ ! -d "$HOME/zenvy" ]; then
            git clone https://github.com/varunudata/zenvy.git $HOME/zenvy
          fi
          cd ~/zenvy
          git pull origin main
          bash scripts/deploy.sh
